from enum import Enum

class GameEndReason(str, Enum):
    DECK_EMPTY = "DECK_EMPTY"
    SECRETS_REVEALED = "SECRETS_REVEALED"
    MURDERER_REVEALED = "MURDERER_REVEALED"

class WinningTeam(str, Enum):
    MURDERERS = "MURDERERS"
    DETECTIVES = "DETECTIVES"

class PlayerRole(str, Enum):
    MURDERER = "MURDERER"
    ACCOMPLICE = "ACCOMPLICE"
    DETECTIVE = "DETECTIVE"

class TurnState(str, Enum):
    IDLE = "IDLE"
    DRAWING_CARDS = "DRAWING_CARDS"
    DISCARDING = "DISCARDING"
    CHOOSING_SECRET = "CHOOSING_SECRET"
    CHOOSING_SECRET_PYS = "CHOOSING_SECRET_PYS"
    END_TURN = "END_TURN"
    PASSING_CARDS = "PASSING_CARDS"
    CARD_TRADE_PENDING = "CARD_TRADE_PENDING"
    CANCELLED_CARD_PENDING = "CANCELLED_CARD_PENDING"
    VOTING = "VOTING"
    PENDING_DEVIOUS = "PENDING_DEVIOUS"
